---
title: "Story Telling With DATA"
output: 
  flexdashboard::flex_dashboard:
     storyboard: true
     social: menu
     source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
```


```{r, include=FALSE, echo = FALSE}
# Import data from custodial-deaths.csv
tx <- read.csv("custodial-deaths.csv", header = TRUE, sep="," , quote = "\"", dec = ".", fill = TRUE, row.names = NULL, stringsAsFactors = FALSE)
df <- as.data.frame(tx)
```

### Custodial deaths in the state of Texas,USA

```{r, echo=FALSE}
library(leaflet)
library(maps)
mapTexas = map("county","texas", fill = TRUE, plot = FALSE)
leaflet(data = mapTexas) %>% addTiles() %>%
  addPolygons(fillColor = rainbow(12, alpha = NULL), stroke = FALSE)

```

***
Counties Include:

- Austin
- Alamo
- Bell
- Bexar
- Brownsville
- Dallas
- Edinburg
- Euless
- Fort Bend
- Fort Worth
- Garland
- Granbury
- Harris
- Houston
- Jasper
- Kerrville
- Longview
- SanAntonio
- Trinity
- RoundRock
- Wharton

### Chart B

```{r, echo=FALSE}
library(plyr)
num <- unique(tx$Department.Name, incomparables = FALSE)
dt <- substr(tx$Death.Date, 1,10)
yr <- substr(dt,1, 4)
date <- as.Date.character(dt, format = "%m-%d-%y")
str(df)

```

### Chart C

```{r, echo=FALSE}
library(dygraphs)
dygraph(tx, main = tx$Department.Name) %>% 
  dyRangeSelector(dateWindow = c("2000-01-01", "2020-01-01"))
```